// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8j6v5vUrNpv1QPd8VeabR3ufsgPYy2o',
    appId: '1:496588237117:web:8ca68d8b1e9b48e8077d54',
    messagingSenderId: '496588237117',
    projectId: 'quizapp-a1bd4',
    authDomain: 'quizapp-a1bd4.firebaseapp.com',
    databaseURL: 'https://quizapp-a1bd4-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-a1bd4.appspot.com',
    measurementId: 'G-Y36QVRCC64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvYRr1ZOFd_NNlfSdeFvigRqAZi2U91U',
    appId: '1:496588237117:android:040d74bc322fd316077d54',
    messagingSenderId: '496588237117',
    projectId: 'quizapp-a1bd4',
    databaseURL: 'https://quizapp-a1bd4-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-a1bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1jj7h2wLaGsc4oaYsWnPrTHEsburDdM',
    appId: '1:496588237117:ios:9e8961bf2d0426a6077d54',
    messagingSenderId: '496588237117',
    projectId: 'quizapp-a1bd4',
    databaseURL: 'https://quizapp-a1bd4-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-a1bd4.appspot.com',
    iosBundleId: 'com.example.pokemonQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1jj7h2wLaGsc4oaYsWnPrTHEsburDdM',
    appId: '1:496588237117:ios:9e8961bf2d0426a6077d54',
    messagingSenderId: '496588237117',
    projectId: 'quizapp-a1bd4',
    databaseURL: 'https://quizapp-a1bd4-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-a1bd4.appspot.com',
    iosBundleId: 'com.example.pokemonQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ8j6v5vUrNpv1QPd8VeabR3ufsgPYy2o',
    appId: '1:496588237117:web:9a5cba0e35ba94df077d54',
    messagingSenderId: '496588237117',
    projectId: 'quizapp-a1bd4',
    authDomain: 'quizapp-a1bd4.firebaseapp.com',
    databaseURL: 'https://quizapp-a1bd4-default-rtdb.firebaseio.com',
    storageBucket: 'quizapp-a1bd4.appspot.com',
    measurementId: 'G-HV8JXPNLRJ',
  );
}
